---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
        - docker.io
